# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 프로필
    url: ko/
    weight: 10
  - name: 경험
    url: ko/experience/
    weight: 20
  - name: 프로젝트
    identifier: projects
    url: ko/projects/
    weight: 30
  - name: 전공
    parent: projects
    url: ko/projects/cs
    weight: 10
  - name: 그 외
    parent: projects
    url: ko/projects/etc
    weight: 11
  - name: 수강과목
    url: ko/courses/
    weight: 40
  - name: 여가
    identifier: others
    url: ko/others/
    weight: 50
