# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 자기소개
    url: ko/
    weight: 10
  - name: 프로젝트
    url: ko/projects
    weight: 20
  - name: 기타 활동
    url: ko/explore
    weight: 30
  - name: 대회
    url: ko/contests
    weight: 40
  - name: 여가
    identifier: others
    url: ko/others
    weight: 50
  - name: 뜨개질
    parent: others
    url: ko/others/knitpurl
    weight: 10
  - name: 여행
    parent: others
    url: ko/others/travel
    weight: 11
  - name: 독서
    parent: others
    url: ko/others/reading
    weight: 12
  - name: Resumé
    url: about/
    weight: 60

# main:
#   - name: 프로필
#     identifier: profile
#     url: ko/
#     weight: 10
#   - name: 요약
#     parent: profile
#     url: ko/#summary
#     weight: 11
#   - name: 수상경력
#     parent: profile
#     url: ko/#award
#     weight: 12
#   - name: 프로젝트
#     url: ko/#project
#     weight: 20
#   - name: 학력 및 경력
#     url: ko/experience/
#     weight: 30
#   - name: 경험
#     url: ko/timeline/
#     weight: 40
#   - name: 여가
#     identifier: others
#     url: ko/others/
#     weight: 50
