# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '전북대학교'
    description: '전북대학교 컴퓨터공학부 22학번 홍사강의 자기소개 페이지입니다. 2024년 2학기 웹서비스설계 과목의 과제로 제작되었습니다.'
    twitter: 'ha_Dah913'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    show_translations: true
    hide_language_name: false
    logo:
      text: "Sakang Hong"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
